Removed react logo from application
googleinterns/play-web-step-2020 pull request #43
Opened 2020-07-07 20:55 UTC by essencec

2020-07-07 21:09 UTC, ajwang0 requested changes

2020-07-07 21:09 UTC, ajwang0 commented on client/src/App.test.js
> -test('verifies fetch is called', async () => {
Don't forget to clean up any unused imports like "wait" from line 3 and renderComponent from line 6

2020-07-07 21:40 UTC, ajwang0 submitted a review, later dismissed

2020-07-07 22:03 UTC, tonymai submitted a review, later dismissed

2020-07-08 16:27 UTC, ajwang0 requested changes
Looks like you have some changes from master that aren't related to ur changes. Can you run rebase from master then force push?

2020-07-08 17:43 UTC, ajwang0 approved these changes

2020-07-08 18:07 UTC, essencec commented
@googlebot I signed it!

2020-07-08 18:08 UTC, merged