Implement material design card component in RecommendedCategories
googleinterns/play-web-step-2020 pull request #52
Opened 2020-07-09 21:27 UTC by essencec

2020-07-09 21:40 UTC, tonymai commented on client/src/Clusters/RecommendedCategories/RecommendedCategories.js
>  import React, { Component } from 'react';
I would use snake case for file names. I.e. recommended_categories.js

Same with the css file below

2020-07-14 18:49 UTC, essencec commented
![Screenshot 2020-07-14 at 2 48 40 PM - Display 2](https://user-images.githubusercontent.com/45109455/87464500-33776e80-c5e1-11ea-8488-2c329243f5e2.png)

2020-07-14 19:08 UTC, tonymai requested changes
Looks good! Just some comments on formatting as well as moving data to the mock cluster.

2020-07-14 19:08 UTC, tonymai commented on client/src/App.js
> +import RecommendedCategories from './Clusters/RecommendedCategories/recommended_categories.js';
why rename this? we should be consistent with our naming convention. generally, I prefer snake_case file names, but it seems like we are already using pascal case format.

i'd be fine with this if we commit to renaming the others to snake case moving forward, though,

2020-07-14 19:08 UTC, tonymai commented on client/src/Clusters/RecommendedCategories/card_container_style.css
> +    width: calc(25% - 20px);
optional: i prefer ordering properties alphabetically

2020-07-14 19:08 UTC, tonymai commented on client/src/Clusters/RecommendedCategories/card_container_style.css
> +    float: left;
what is this `float` for? prefer refrain from using floats if possible. most styling can be achieved without it

2020-07-14 19:08 UTC, tonymai commented on client/src/Clusters/RecommendedCategories/card_container_style.css
> +    font-size: 25px;
Let's true to use `rem` instead of `px`. It makes it easier to make the font size more responsive later.

2020-07-14 19:08 UTC, tonymai commented on client/src/Clusters/RecommendedCategories/recommended_categories.js
> +                    <h6>Didn't find what you're looking for?</h6>
Please move the title and subtitle into the mock cluster. All data should be coming from the back end. The front end should only be concerned with data placement and styling

2020-07-14 19:08 UTC, tonymai commented on client/src/Clusters/RecommendedCategories/recommended_categories.js
> +                <a href="https://play.google.com/">See all categories</a>
Same here, move to mock cluster. Something like:

```
cluster = {
   ...
   navigation: {
      text: "See all categories",
      url: "https://play.google.com/",
   }
}

2020-07-14 19:32 UTC, essencec commented on client/src/App.js
> +import RecommendedCategories from './Clusters/RecommendedCategories/recommended_categories.js';
You mentioned it in a previous comment, so I changed it to snake_case. Should I change them back?

2020-07-14 19:36 UTC, tonymai commented on client/src/App.js
> +import RecommendedCategories from './Clusters/RecommendedCategories/recommended_categories.js';
That's fine then. Let's commit to changing file names to snake case as we touch them.

2020-07-14 20:39 UTC, tonymai submitted a review, later dismissed

2020-07-15 00:06 UTC, ajwang0 approved these changes
LGTM

2020-07-15 00:13 UTC, merged