Replace mocked data in Top Charts with data from java servlet stream
googleinterns/play-web-step-2020 pull request #65
Opened 2020-07-20 18:23 UTC by essencec

2020-07-20 18:26 UTC, essencec commented
![image](https://user-images.githubusercontent.com/45109455/87972482-f6a1f080-ca94-11ea-9278-bce550d2f967.png)

2020-07-20 19:08 UTC, ajwang0 requested changes

2020-07-20 19:08 UTC, ajwang0 commented on client/src/Clusters/TopCharts/TopCharts.js
> +            console.log(chart)
Remove log

2020-07-20 19:08 UTC, ajwang0 commented on client/src/App.js
> +            return <TopCharts data={cluster} key={cluster.id} />
Can you indent the return so its easier to read

2020-07-20 20:53 UTC, ajwang0 requested changes

2020-07-20 20:53 UTC, ajwang0 commented on src/main/java/com/google/sps/models/TopChartsCluster.java
>      private ArrayList<Chart> charts = new ArrayList<Chart>();
Can you also update this to use List 

`private List<Chart> charts = new ArrayList<Chart>();`

2020-07-20 20:53 UTC, ajwang0 commented on src/main/java/com/google/sps/models/Cluster.java
> +    String type;
Can you add a new line inbetween String type and the methods

2020-07-20 20:55 UTC, ajwang0 requested changes
I think you'll need to update the test for App.js to use the FetchMock like in https://github.com/googleinterns/play-web-step-2020/pull/36/files#diff-648495ee1d77c291870f467735fd9493

2020-07-21 16:38 UTC, ajwang0 requested changes

2020-07-21 16:38 UTC, ajwang0 commented on src/main/java/com/google/sps/models/TopChartsCluster.java
>  import java.util.ArrayList;
Don't forget to also add `import java.util.List;`

2020-07-21 16:38 UTC, ajwang0 commented on client/src/App.js
> +            if(response.status == 200) {
Add space after if and use 3 equals

`if (response.status === 200) {`

2020-07-21 18:17 UTC, tonymai submitted a review, later dismissed

2020-07-21 18:17 UTC, tonymai commented on client/src/App.js
> +    this.state = { streamData: null };
`this.state = {}`

2020-07-21 18:17 UTC, tonymai commented on client/src/App.js
> +    if (this.state.streamData == null) {
use triple equal signs, `===`

![image](https://user-images.githubusercontent.com/9425367/88091174-8bfbbe00-cb43-11ea-9ce4-08d5f0740f1c.png)

2020-07-21 18:17 UTC, tonymai commented on client/src/Clusters/TopCharts/TopCharts.js
> +
remove spaces

2020-07-22 18:35 UTC, ajwang0 requested changes

2020-07-22 18:35 UTC, ajwang0 commented on client/src/App.test.js
> +          matcher: '/api/v1/stream', method: 'GET', response: {"clusters":[{"title":"Top Charts","subtitle":"For Wear OS","charts":[{"title":"Top Free","apps":[{"id":"1","icon":"mockIcon1.png","title
Can you make a variable for the response and move the data into the var so this is cleaner to read?

```
const responseData = {"clusters": ...};

...
matcher: '/api/v1/stream', method: 'GET', response: responseData

```

2020-07-22 18:35 UTC, ajwang0 commented on client/src/App.test.js
> +test('verifies fetch is called from Top Charts', async () => {
I would rename this to "fetch returns data for Top Charts cluster"

2020-07-22 18:35 UTC, ajwang0 commented on client/src/App.test.js
> +test('verifies nothing is rendered if streamData is set to null', async () => {
I would rename this to "nothing is rendered when fetch fails"

2020-07-22 18:35 UTC, ajwang0 commented on client/src/Clusters/TopCharts/TopCharts.js
> +    if (data == null) {
We can omit this since we only render TopCharts when App.js finds a TopCharts in the data.

2020-07-22 18:35 UTC, ajwang0 commented on client/src/Clusters/TopCharts/TopCharts.js
>  class TopCharts extends Component {
Can you also add PropTypes for this. At the minimum at least define data is a required object

2020-07-22 18:35 UTC, ajwang0 commented on client/src/Clusters/TopCharts/topCharts.test.js
> +test('correct column titles', async() => {
Can you also verify the App cards are in the DOM?

2020-07-22 21:41 UTC, ajwang0 approved these changes

2020-07-22 21:52 UTC, essencec commented
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and then comment `@googlebot I fixed it.`. If the bot doesn't comment, it means it doesn't think anything has changed.
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogleinterns%2Fplay-web-step-2020%2Fpull%2F65) for more info**.

@googlebot I fixed it

2020-07-22 21:52 UTC, ajwang0 approved these changes

2020-07-22 21:54 UTC, merged